<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Pedidos2.aspx.cs" Inherits="Site.Pedidos.Pedidos2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/pedidos.css" rel="stylesheet" />

    <script src="/Scripts/jquery-1.9.0.min.js"></script>
    <script src="/Scripts/bootstrap.min.js"></script>
    <script src="/Scripts/jquery.maskMoney.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />'); 
            else $('head > link').filter(':first').replaceWith(defaultCSS); 
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height()); 
          //window.parent.postMessage( iframe_height, 'http://bootsnipp.com');
        });

        function newAlert(type, message) {
            $("#alert-area").append($("<div class='alert-message " + type + " fade in' data-alert><p> " + message + " </p></div>"));
            $(".alert-message").delay(8000).fadeOut("slow", function () { $(this).remove(); });
        }

        function newSucess(message)
        {
            $("#success-alert").removeClass("invisible");
            $("#success-alert").append($("<div class='text-center'><strong> " + message + "</strong></div>"));
            $("#success-alert").fadeTo(30000, 500).slideUp(500, function () {
                $("#success-alert").alert('close');
            });

            //$("#alert-area").append($("<div class='alert alert-success fade in' data-alert><p> " + message + " </p></div>"));
            //$(".alert-message").delay(8000).fadeOut("slow", function () { $(this).remove(); });
        }

        function newAlert(message) {
            $("#danger-alert").removeClass("invisible");
            $("#danger-alert").append($("<div class='text-center'><strong> " + message + "</strong></div>"));
            $("#danger-alert").fadeTo(10000, 500).slideUp(500, function () {
                $("#danger-alert").alert('close');
            });

            //$("#alert-area").append($("<div class='alert alert-success fade in' data-alert><p> " + message + " </p></div>"));
            //$(".alert-message").delay(8000).fadeOut("slow", function () { $(this).remove(); });
        }

        //newAlert('success', 'Oh yeah!');

        $(function () {
            $("#ctl00_ContentPlaceHolder1_txtValor").maskMoney({ showSymbol: true, symbol: "R$", decimal: ",", thousands: "." });
        })
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <asp:ValidationSummary ID="ValidationSummary1" runat="server" />
    <div class="container">
         <div class="row">
            <div class="col-md-12">
               

              <Wizard:WizardGridView ID="gvListaPedidos" runat="server" DataSourceID="SourceData" DataKeyNames="idPedido" OnRowCommand="gvListaPedidos_RowCommand" 
         ShowHeaderWhenEmpty="false"  OnRowDataBound="gvListaPedidos_RowDataBound" AutoGenerateColumns="false"  CssClass="table table-hover"   ClientIDMode="Static" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" PageSize="20" AllowPaging="true"   >
       <Columns>
            <%--<EditItemTemplate>
                    <asp:DropDownList ID="ddlLevel" runat="server" />
                </EditItemTemplate>--%>
            <asp:TemplateField HeaderText="idDet">
                <ItemTemplate>
                    <asp:Label ID="lblidPedDet" Width="30px" runat="server" Text='<%#Eval("idDetPed") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="idPedido">
                <ItemTemplate>
                    <asp:Label ID="lblIdPedido" Width="30px" runat="server" Text='<%#Eval("idPedido") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="Tipo">
                <ItemTemplate>
                    <asp:Label ID="lblTipoPedido" Width="30px" runat="server" Text='<%#Eval("Tipo") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="Opção">
                <ItemTemplate>
                    <asp:Label ID="lblOpcao" Width="80px" runat="server" Text='<%#Eval("Opcao") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="Sabor">
                <ItemTemplate>
                    <asp:Label ID="lblSabor" Width="250px" runat="server" Text='<%#Eval("sabor") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="Qtd">
                <ItemTemplate>
                    <asp:Label ID="lblQtd" Width="30px" runat="server" Text='<%#Eval("qtd") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="Valor">
                <ItemTemplate>
                    <asp:Label ID="lblValor" Width="30px" runat="server" Text='<%#Eval("valor") %>' />
                </ItemTemplate>
            </asp:TemplateField>
           <asp:TemplateField HeaderText="Status">
                <ItemTemplate>
                    <asp:Label ID="lblStatusPedido" Width="30px" runat="server" Text='<%#Eval("statusPedido") %>' />
                </ItemTemplate>
            </asp:TemplateField>
       </Columns>
    </Wizard:WizardGridView>
            </div>
        </div>
    </div>
    <asp:ObjectDataSource ID="SourceData" TypeName="BLL.Pedidos.PedidosBLL" SelectMethod="obterDataSet" runat="server"></asp:ObjectDataSource>

        <div class="container">
  <div class="row" id="container">
    <div class="col-md-4"></div>
     <div class="col-md-4 text-center">
         <div id="alert-area" style="width:420px;"></div>
         

     <div class="formulario">   
         <h1>Pedido</h1>
         <section class="login-form">
                <asp:ValidationSummary ID="ValidationSummary2" runat="server" Visible="false" />
                <asp:Panel ID="panelFormulario" runat="server" DefaultButton="cmdSalvar">
                <div class="col-md-12">
                     <asp:DropDownList ID="ddlTipoProdutos" runat="server" CssClass="form-control espaco" Width="340px" OnSelectedIndexChanged="ddlTipoProdutos_SelectedIndexChanged" AutoPostBack="true">
                </asp:DropDownList>
                </div>

                <div class="col-md-12">
                     <asp:DropDownList ID="ddlOpcao" runat="server" CssClass="form-control espaco" Width="340px" OnSelectedIndexChanged="ddlOpcao_SelectedIndexChanged" Visible="false" AutoPostBack="true">
                </asp:DropDownList>
                </div>
                <div class="col-md-12">
                     <asp:DropDownList ID="ddlSabor1" runat="server" CssClass="form-control espaco" Width="340px" Visible="false" OnSelectedIndexChanged="ddlSabor_SelectedIndexChanged" AutoPostBack="true" >
                </asp:DropDownList>
                </div>
                <div class="col-md-12">
                     <asp:DropDownList ID="ddlSabor2" runat="server" CssClass="form-control espaco" Width="340px"  Visible="false" OnSelectedIndexChanged="ddlSabor_SelectedIndexChanged" AutoPostBack="true">
                </asp:DropDownList>
                </div>
                <div class="col-md-12">
                     <asp:DropDownList ID="ddlSabor3" runat="server" CssClass="form-control espaco" Width="340px"  Visible="false" OnSelectedIndexChanged="ddlSabor_SelectedIndexChanged" AutoPostBack="true">
                </asp:DropDownList>
                </div>
                <div class="col-md-12">
                     <asp:DropDownList ID="ddlQtd" runat="server" CssClass="form-control espaco" Width="340px" OnSelectedIndexChanged="ddlQtd_SelectedIndexChanged" AutoPostBack="true" >
                </asp:DropDownList>
                </div>    
                 <div class="col-md-12">
                    <div class="[ form-group ]" id="divBorda" runat="server" >
                        <input type="checkbox" name="fancyCheckBox" id="fancyCheckBox" autocomplete="off" runat="server"  ClientIDMode="Static" />
                        <div class="[ btn-group ]">
                            <label for="fancyCheckBox" class="[ btn btn-default ]">
                                <span class="[ glyphicon glyphicon-ok ]"></span>
                                <span> </span>
                            </label>
                            <label for="fancyCheckBox" class="[ btn btn-default  ] tamanhoCheckBox">
                                Borda Recheada
                            </label>
                        </div>
                    </div>
                </div>     
                <div class="col-md-12">
                     <asp:DropDownList ID="ddlBorda" runat="server" CssClass="form-control espaco" Width="340px"  AutoPostBack="true" >
                </asp:DropDownList>
                </div>  




                    <div class="col-md-12">
                        <div class="col-md-6">
                            <asp:Button ID="cmdVoltar" runat="server" Text="Voltar" OnClick="cmdVoltar_Click" CssClass="btn btn-lg btn-danger btn-block botaoVoltar" CausesValidation="false" UseSubmitBehavior="false" />&nbsp;
                         </div>
                        <div class="col-md-6">
                            <asp:Button ID="cmdSalvar" runat="server" Text="Adicionar" OnClick="cmdSalvar_Click" CssClass="btn btn-lg btn-primary btn-block botaoSalvar" />
                        </div>
                    </div>
                    <div class="col-md-12">
                        <%--<div class="col-md-6">
                            <asp:Button ID="Button1" runat="server" Text="Voltar" OnClick="cmdVoltar_Click" CssClass="btn btn-lg btn-danger btn-block botaoVoltar" CausesValidation="false" UseSubmitBehavior="false" />&nbsp;
                         </div>--%>
                            <asp:Button ID="cmdFinalizar" runat="server" Text="Finalizar" OnClick="cmdFinalizar_Click" CssClass="btn btn-lg btn-success btn-block botaoFinalizar" />
                        
                    </div>

                    <div class="row">

                    </div>
        
    </asp:Panel>
              
        </section>
     </div>
    </div>
    <div class="col-md-2"></div>
    
      <div class="col-md-2">
        <div class="alert alert-success invisible" id="success-alert">
            <button type="button" class="close" data-dismiss="alert">x</button>
        </div>
        <div class="alert alert-danger invisible" id="danger-alert">
            <button type="button" class="close" data-dismiss="alert">x</button>
        </div>

    </div>
  </div>
</div>




</asp:Content>
